#!/bin/bash
#2021-10-08
#Script to archive all openMower dependencies to support cross compiler requirements
#To be run on target system (raspberry pi)

#Noetic 
tar cvfh ~/cross-compile-libs.tar /opt/ros/noetic/
#/usr/lib/aarch64-linux-gnu
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/cmake
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/librt*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libopencv* 
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpthread*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libboost*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libdl*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libconsole_bridge*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libsuitesparseconfig*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcholmod*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libPocoFoundation* 
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpython* 
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libtinyxml2* 
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liblz4*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liblog4cxx*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libz*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libtbb*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libbz2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libapr-1*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libaprutil-1*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libicui18n*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libicuuc*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libjpeg*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libwebp*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpng16*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmMSFF*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libtiff*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libIlmImf-2_3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmDSED*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpcre*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libexpat*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libutil*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libuuid*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcrypt*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libicudata*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmDICT*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmjpeg8*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmjpeg12*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmjpeg16*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libopenjp2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libCharLS*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libjson-c*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmIOD*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgdcmCommon*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liblzma*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libjbig*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libHalf*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libIex-2_3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libIlmThread-2_3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpoppler*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libfreexl*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libqhull*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgeos_c*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libepsilon*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libodbc*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libodbcinst*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libkmlbase*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libkmldom*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libkmlengine*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libxerces-c-3.2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libnetcdf*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libhdf5_serial*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgif*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgeotiff*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcfitsio*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpq*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libproj*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libdapclient*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libdap*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libspatialite*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcurl-gnutls*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libfyba*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libxml2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libmysqlclient*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libblas*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liblapack*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libarpack*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libsuperlu*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libfreetype*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libfontconfig*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liblcms2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libnss3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libsmime3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libnspr4*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgeos-3.8.0*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libltdl*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libminizip*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liburiparser*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libsz*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libssl*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgssapi_krb5*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libldap_r-2.4*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libsqlite3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libnghttp2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libidn2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libssh*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libpsl*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libnettle*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgnutls*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/liblber-2.4*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libbrotlidec*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libfyut*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libfygm*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libresolv*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libhogweed*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgmp*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgfortran*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libnssutil3*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libplc4*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libplds4*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libaec*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libkrb5*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libk5crypto*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcom_err*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libkrb5support*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libsasl2*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libgssapi*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libunistring*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libp11-kit*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libtasn1*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libbrotlicommon*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libkeyutils*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libheimntlm*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libasn1*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libhcrypto*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libroken*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libffi*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libwind*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libheimbase*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libhx509*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libamd*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libbtf*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcamd*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libccolamd*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcolamd*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libcxsparse*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libklu*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libumfpack*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libyaml*
tar uvfh ~/cross-compile-libs.tar /usr/lib/aarch64-linux-gnu/libGeographic*
#/usr/lib
tar uvfh ~/cross-compile-libs.tar /usr/lib/libmfhdfalt*
tar uvfh ~/cross-compile-libs.tar /usr/lib/libdfalt*
tar uvfh ~/cross-compile-libs.tar /usr/lib/libogdi*
tar uvfh ~/cross-compile-libs.tar /usr/lib/libarmadillo*
tar uvfh ~/cross-compile-libs.tar /usr/lib/liborocos*
tar uvfh ~/cross-compile-libs.tar /usr/lib/libgdal*
#/usr/include
tar uvfh ~/cross-compile-libs.tar /usr/include/opencv4
tar uvfh ~/cross-compile-libs.tar /usr/include/boost
tar uvfh ~/cross-compile-libs.tar /usr/include/log4cxx
tar uvfh ~/cross-compile-libs.tar /usr/include/kdl
tar uvfh ~/cross-compile-libs.tar /usr/include/eigen3
tar uvfh ~/cross-compile-libs.tar /usr/include/console_bridge
tar uvfh ~/cross-compile-libs.tar /usr/include/suitesparse
tar uvfh ~/cross-compile-libs.tar /usr/include/Poco
tar uvfh ~/cross-compile-libs.tar /usr/include/gdal
tar uvfh ~/cross-compile-libs.tar /usr/include/GeographicLib
tar uvfh ~/cross-compile-libs.tar /usr/include/bzlib.h
tar uvfh ~/cross-compile-libs.tar /usr/include/lz4.h
tar uvfh ~/cross-compile-libs.tar /usr/include/console_bridge_export.h
tar uvfh ~/cross-compile-libs.tar /usr/include/tinyxml2.h
#/usr/share
tar uvfh ~/cross-compile-libs.tar /usr/share/orocos_kdl

gzip -f cross-compile-libs.tar